# Generated by Django 2.2.7 on 2019-11-14 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20191114_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 15, 46, 32, 485771), null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 15, 46, 32, 485771), null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 15, 46, 32, 485771), null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 15, 46, 32, 485771), null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 15, 46, 32, 485771), null=True),
        ),
    ]
