# Generated by Django 2.2.7 on 2019-11-14 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20191114_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 21, 35, 46, 688643), null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 21, 35, 46, 688643), null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 21, 35, 46, 688643), null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 21, 35, 46, 687642), null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 21, 35, 46, 687642), null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
