# Generated by Django 2.2.7 on 2019-11-14 18:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0008_auto_20191114_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 21, 36, 9, 34348), null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 21, 36, 9, 34348), null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 21, 36, 9, 34348), null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 21, 36, 9, 33363), null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 14, 21, 36, 9, 33363), null=True),
        ),
    ]
